services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_pcdoc
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: produtos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend-desafio
    container_name: backend_pcdoc
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/produtos_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

  frontend:
    build: ./frontend-desafio
    container_name: frontend_pcdoc
    ports:
      - "4200:4200"
    depends_on:
      - api

volumes:
  postgres_data: