spring.application.name=backend-desafio

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/produtos_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update